name: CI
on:
  workflow_dispatch:
   inputs:
    Number-1:
     description: 'First-Number'
     required: true
    
    Number-2:
     description: 'Second-Number'
     required: true

env:
 File1: Sum.py
 File2: Prime.py
 num1: ${{ github.event.inputs.First-Number }}
 num2: ${{ github.event.inputs.second-Number }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
         python $File1 $num1 $num2
         python $File2 $num1 $num2